### ISSUE TITLE
Testing points for v2 release

### ISSUE THREAD

**Issue by yakshaG** [sadanandpai/resume-builder#110]
## Hide eye icon, since it is not functional
![image](https://user-images.githubusercontent.com/26523871/189724068-0cba94ba-eab8-47de-a54e-36e63683347e.png)

---

## Clean up default values of rich text editor in all places
- Company 1 details look well formatted
- Company 2 details are not parsed and shown as is

![image](https://user-images.githubusercontent.com/26523871/189725196-ef8af244-81f6-465d-866b-afcf54e28eba.png)

---

## Activities/volunteering data not used in any template
Potential for user to get confused. Possible options:
- Add a message inside activities section saying `This data is currently not being used by any template`
- Hide `Activities` from the main side panel

**Comment by gopal1996** [comment]
Above issues has been addressed
