### ISSUE TITLE
Can you help me how i deploy and execute build command please?

### ISSUE THREAD

**Issue by davidCarr99** [sadanandpai/resume-builder#120]
#### 
I want to perform a deployment and compress the files using the build command, but when doing the process, the files are compressed very differently

What should be the expected result?

#### 
![image](https://user-images.githubusercontent.com/69122360/204049660-12cb1aee-1d56-49cd-9c49-ab454b5c0986.png)

What is the result now?

**Comment by sadanandpai** [comment]
This looks right. As it is SSR supported you can use vercel or netlify to deploy

**Comment by sadanandpai** [comment]
Closing the issue due to no response.
