### ISSUE TITLE
v1 Deployment

### ISSUE THREAD

**Issue by RuthlessRuler** [sadanandpai/resume-builder#139]
Hi,

I wanted to know where can I access the previous version website as I had created my Resume doing it and some features like Markdown and custom Title name are missing in this version.

If the deployment is not available, can you point out the last commit of v1 and steps to build/deploy on GH Page ?

**Comment by sadanandpai** [comment]
Hi, 

We have the source code for the same in releases for version 1

https://github.com/sadanandpai/resume-builder/releases

**Comment by RuthlessRuler** [comment]
Thanks alot for the help.

I have deployed it: https://resume-v1-lovat.vercel.app/
Repo: https://github.com/RuthlessRuler/resume-v1
