### ISSUE TITLE
Option to disable the Percentage known for a select skill

### ISSUE THREAD

**Issue by Anirban-1490** [sadanandpai/resume-builder#144]
#### Is your feature request related to a problem? Please describe.

Really would like a option to disable the percentage bar for the languages

#### Describe the solution you'd like

a simple option to toggle off the sliders when showing the languages .

Toggle this off 

![Opera Snapshot_2023-01-10_115753_e-resume vercel app](https://user-images.githubusercontent.com/82874704/211478028-6030e85e-e1a2-4f72-a4bd-6cef404bb132.png)

after toggling it off it should look like this - 

![Opera Snapshot_2023-01-10_120121_e-resume vercel app](https://user-images.githubusercontent.com/82874704/211478204-44eb01c2-06f8-4e4e-a456-1225a75b0d01.png)

**Comment by suprabhat15** [comment]
Hey @sadanandpai, I am interested to work on it.

**Comment by gopal1996** [comment]
This purely depends on the resume template creator. we will add multiple templates without percentage bar in futures
