### ISSUE TITLE
Edit option support for skill section

### ISSUE THREAD

**Issue by gopal1996** [sadanandpai/resume-builder#161]
If skill is already added, we can't edit the value. either we need to delete or re-add that. we must support editing the existing data

**Comment by yakshaG** [comment]
Refer Figma for screens.

![image](https://user-images.githubusercontent.com/26523871/214596098-1f09f743-d4c8-4540-a1e3-7f7af7568a33.png)

![image](https://user-images.githubusercontent.com/26523871/214596192-f65a186c-acfd-4bfc-b670-1d79f1c4d2fd.png)

**Comment by s-ashwin** [comment]
Can i get this assigned?

**Comment by s-ashwin** [comment]
Also, can i get the design file?

**Comment by siva-kannan3** [comment]
> Also, can i get the design file?

@yakshaG can you share the design file here?

**Comment by yakshaG** [comment]
@s-ashwin shared invite to the design file on your gmail id.

**Comment by s-ashwin** [comment]
> @s-ashwin shared invite to the design file on your gmail id.

Checked that. Seems like i don't have the option to export the edit icon. Could you help me reg this?

**Comment by yakshaG** [comment]
![edit-icon](https://user-images.githubusercontent.com/26523871/221218907-e235aae4-60cb-4c32-9935-da4e8deb1f31.svg)


Here you go
