### ISSUE TITLE
Export/Import resume data to json

### ISSUE THREAD

**Issue by cushychandru** [sadanandpai/resume-builder#37]
**Hi  @sadanandpai ,**

**a warm appreciation for your efforts towards opensource.**

**_It would be great if we can able to Export/Import resume data to json , this will be good if we can to edit the resume in the future._**

Please feel free to contact me if any help needed 

Thanks in advance

**Comment by sadanandpai** [comment]
@cushychandru thanks for suggesting the important feature. Will try to integrate that soon

**Comment by sadanandpai** [comment]
@gopal1996

**Comment by Nitin6118** [comment]
@sadanandpai - Also, requesting you to integrate the export feature to .doc(word)

**Comment by sadanandpai** [comment]
Export and import features have been added
