### ISSUE TITLE
Unwanted colon in the intro

### ISSUE THREAD

**Issue by Nitin6118** [sadanandpai/resume-builder#40]
#### Issue
Unwanted colon in the intro

#### Bug description

I just wanted to specify Total Experience and remove Relevant Experience; it's giving default colon even after making Relevant Experience is empty

#### Steps to reproduce

Just try to empty/remove one of the default experiences

**Comment by sadanandpai** [comment]
@Nitin6118 Fixed the issue by adding the check if label for experience exists or not. (both relevant and total)
![image](https://user-images.githubusercontent.com/12962887/148671352-01ae9935-224b-4f9e-980a-c6a7b81d3c91.png)
Please verify

**Comment by Nitin6118** [comment]
@sadanandpai - That was quick, thanks for doing this great work and making it available for everyone.
