### ISSUE TITLE
2 pages resume- template

### ISSUE THREAD

**Issue by shivprasad94** [sadanandpai/resume-builder#48]
Hi, I come from AI and ML Background, and most of our projects needs bit of detail description related to End to End pipeline of the project..
 I actually want "Projects section" in Pages 2 rest all template in page on as it is.... Something like below..

![Screenshot 2022-03-19 112252](https://user-images.githubusercontent.com/13836633/159109467-316a2c43-7f20-45f9-86a5-a72d873b5164.jpg)

I tried Converting save 1 page Pdf to world Doc and started editing but few OCR related things were Not editable and was saved as Image

**Comment by sadanandpai** [comment]
The resume is made for pdf format and further editing in the future is suggested with the copy of JSON. As the many elements are word incompatible, word file is not suggested.

As of now, it is designed for single page; may consider multipage in future
