### ISSUE TITLE
Changes introduced by home page refactoring

### ISSUE THREAD

**Issue by yakshaG** [sadanandpai/resume-builder#84]
The changes have been mentioned below with expected behaviour and what is actually present now.

| Expected | Actual |
| --- | --- |
| Headshake animation of hero image on load and on hover |  Animation removed |
| ![image](https://user-images.githubusercontent.com/26523871/170831523-5e16bf7c-bce9-42ab-94b9-8183953a948a.png) | ![image](https://user-images.githubusercontent.com/26523871/170831560-3c216e94-0009-4e54-8697-0c4cbb4c67f4.png) |
| ![image](https://user-images.githubusercontent.com/26523871/170831612-158c2522-d999-4fe3-a9e7-ee657e876a78.png) |  Note the shadow being cut off for the image and lesser margin between image and name  <br />  ![image](https://user-images.githubusercontent.com/26523871/170831754-aae3317a-2a94-42c8-b8ca-6f93b24fcd69.png) |

<br /> <br />

**Comment by gopal1996** [comment]
Style issue fixed
