### ISSUE TITLE
option to add Companies Logo beside Company Name 

### ISSUE THREAD

**Issue by shivprasad94** [sadanandpai/resume-builder#91]
I would Highly recommend to add a optional feature to add company Logo beside Company Name to looks visually more appealing. 
we already have too much text content on Experience, Key Projects / Involvements and Certificates and Awards, so something like below would look amazing.

![image](https://user-images.githubusercontent.com/13836633/180407105-14ece356-3c0e-484f-bb2e-2f4664f88ffa.png)

Just like how LinkedIn shows company on profile. 
Very less online resume template gives such option to add logo..

**Comment by sadanandpai** [comment]
noted

**Comment by shivprasad94** [comment]
Any update on when is the next Major update to your Repo? and when can you add this Company Logo feature. 
**I am desperately waiting for this feature.** 😂

**Comment by sadanandpai** [comment]
we are working on V2 version of the resume builder. It may take couple of more months. No ETA as of now. But will keep you updated

**Comment by gopal1996** [comment]
added to the roadmap. we will update once done

**Comment by judetrimble** [comment]
Any update on this.

**Comment by sadanandpai** [comment]
We are not taking new changes as we do not have bandwidth
